### ISSUE TITLE
Topのメニューの並びは逆にした方が良い？

### ISSUE THREAD

**Issue by ocean3fish** [LinkedOpenData/challenge2020#2]
Topのメニューの並びが意図せず逆になっているということはないでしょうか？

現状のメニューの並び
<img width="1440" alt="スクリーンショット 2020-07-04 22 08 43" src="https://user-images.githubusercontent.com/4206675/86513183-1dc8b300-be43-11ea-84a0-9e4fbfad795f.png">

2019年サイトでのメニューの並び
<img width="1440" alt="スクリーンショット 2020-07-04 22 10 41" src="https://user-images.githubusercontent.com/4206675/86513209-4486e980-be43-11ea-979d-61b8533224ba.png">

**Comment by fumi** [comment]
Fixed at 9ada6128d60be1b20ba1f53cb69f373f1249dc01
